build behaviortree:
  image: ubuntu
  script:
    - apt update
    - sudo apt-get install libzmq3-dev libboost-coroutine-dev libncurses5-dev libncursesw5-dev
    - sudo apt install build-essential
    - mkdir build; cd build
    - cmake
    - make
    - sudo make install
