build behaviortree:
  image: ubuntu
  script:
    - apt update
    - apt-get install libzmq3-dev libboost-coroutine-dev libncurses5-dev libncursesw5-dev -y
    - apt install build-essential -y
    - mkdir build; cd build
    - apt install cmake -y
    - cmake ..
    - make
    - make install
